# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # I'm using this because it's already available on my machine.
  # Most any box will do.
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.name = "vssh test box"
  end
end
